/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as VerifyTicketCodeRouteImport } from './routes/verify.$ticketCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTicketCodeRoute = VerifyTicketCodeRouteImport.update({
  id: '/verify/$ticketCode',
  path: '/verify/$ticketCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agencies': typeof AgenciesRoute
  '/auth': typeof AuthRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/stations': typeof StationsRoute
  '/tickets': typeof TicketsRoute
  '/timetable': typeof TimetableRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/verify/$ticketCode': typeof VerifyTicketCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agencies': typeof AgenciesRoute
  '/auth': typeof AuthRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/stations': typeof StationsRoute
  '/tickets': typeof TicketsRoute
  '/timetable': typeof TimetableRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/verify/$ticketCode': typeof VerifyTicketCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agencies': typeof AgenciesRoute
  '/auth': typeof AuthRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/stations': typeof StationsRoute
  '/tickets': typeof TicketsRoute
  '/timetable': typeof TimetableRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/verify/$ticketCode': typeof VerifyTicketCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agencies'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/stations'
    | '/tickets'
    | '/timetable'
    | '/auth/confirm'
    | '/booking/$bookingId'
    | '/trips/$tripId'
    | '/verify/$ticketCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agencies'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/stations'
    | '/tickets'
    | '/timetable'
    | '/auth/confirm'
    | '/booking/$bookingId'
    | '/trips/$tripId'
    | '/verify/$ticketCode'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agencies'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/stations'
    | '/tickets'
    | '/timetable'
    | '/auth/confirm'
    | '/booking/$bookingId'
    | '/trips/$tripId'
    | '/verify/$ticketCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgenciesRoute: typeof AgenciesRoute
  AuthRoute: typeof AuthRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  StationsRoute: typeof StationsRoute
  TicketsRoute: typeof TicketsRoute
  TimetableRoute: typeof TimetableRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  VerifyTicketCodeRoute: typeof VerifyTicketCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$ticketCode': {
      id: '/verify/$ticketCode'
      path: '/verify/$ticketCode'
      fullPath: '/verify/$ticketCode'
      preLoaderRoute: typeof VerifyTicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthConfirmRoute: typeof AuthConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmRoute: AuthConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgenciesRoute: AgenciesRoute,
  AuthRoute: AuthRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  StationsRoute: StationsRoute,
  TicketsRoute: TicketsRoute,
  TimetableRoute: TimetableRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  VerifyTicketCodeRoute: VerifyTicketCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
